Repository DiFve/YIMS, pull requests merged in 2021-04, with the labels that each got.

#17 -Special Card Bug Fixed
  build/built-jar.properties
  build/classes/yimsbean/Deck.class
  build/classes/yimsbean/Player.class
  src/yimsbean/Deck.java
  src/yimsbean/Player.java
Labels: By KJ, bug-fixed

#19 Jark
  README.md
  build/classes/.netbeans_automatic_build
  build/classes/.netbeans_update_resources
  build/classes/yimsbean/Card.class
  build/classes/yimsbean/Deck.class
  build/classes/yimsbean/Game.class
  build/classes/yimsbean/InGameUI.fxml
  build/classes/yimsbean/MainController.class
  build/classes/yimsbean/MainMenu.class
  build/classes/yimsbean/MainMenuController.class
  build/classes/yimsbean/Player.class
  build/classes/yimsbean/YIMSBean.class
  nbproject/private/private.properties
  nbproject/private/private.xml
  nbproject/project.properties
  src/yimsbean/Deck.java
  src/yimsbean/Game.java
  src/yimsbean/InGameUI.fxml
  src/yimsbean/MainController.java
  src/yimsbean/MainMenu.java
  src/yimsbean/MainMenuController.java
  src/yimsbean/YIMSBean.java
Labels: bug

#20 Kawjaw
  .gitignore
  build/built-jar.properties
  build/classes/.netbeans_automatic_build
  build/classes/.netbeans_update_resources
  build/classes/yimsbean/Card.class
  build/classes/yimsbean/Deck.class
  build/classes/yimsbean/MainController.class
  build/classes/yimsbean/MainMenuController.class
  build/classes/yimsbean/Player.class
  build/classes/yimsbean/YIMSBean.class
  nbproject/private/private.properties
  nbproject/private/private.xml
  nbproject/project.properties
  src/yimsbean/YIMSBean.java
Labels: By KJ, bug-fixed

#22 add enemy add animate
  nbproject/private/private.properties
  nbproject/project.properties
Labels: add

#24 -added specialCard1 effect -continueBtnBug??
  build/built-jar.properties
  build/classes/.netbeans_automatic_build
  build/classes/.netbeans_update_resources
  build/classes/sound/soundController.class
  build/classes/yimsbean/Card.class
  build/classes/yimsbean/CreditController.class
  build/classes/yimsbean/Deck.class
  build/classes/yimsbean/Enemy.class
  build/classes/yimsbean/InGameUI.fxml
  build/classes/yimsbean/MainController.class
  build/classes/yimsbean/MainMenuController.class
  build/classes/yimsbean/Player.class
  build/classes/yimsbean/YIMSBean.class
  nbproject/private/private.properties
  nbproject/private/private.xml
  nbproject/project.properties
  src/yimsbean/Card.java
  src/yimsbean/Deck.java
  src/yimsbean/Enemy.java
  src/yimsbean/InGameUI.fxml
  src/yimsbean/MainController.java
  src/yimsbean/Player.java
Labels: By KJ, add, bug

#26 -bug fixed -added SpecialCardEffect2
  build/built-jar.properties
  build/classes/.netbeans_automatic_build
  build/classes/.netbeans_update_resources
  build/classes/sound/soundController.class
  build/classes/yimsbean/Card.class
  build/classes/yimsbean/CreditController.class
  build/classes/yimsbean/Deck.class
  build/classes/yimsbean/Enemy.class
  build/classes/yimsbean/MainController.class
  build/classes/yimsbean/MainMenuController.class
  build/classes/yimsbean/Player.class
  build/classes/yimsbean/YIMSBean.class
  nbproject/private/private.properties
  nbproject/project.properties
  src/yimsbean/Deck.java
  src/yimsbean/Enemy.java
  src/yimsbean/MainController.java
  src/yimsbean/Player.java
Labels: By KJ, add, bug-fixed

#29 -add SpecialCardEffect2 -fixed a tons of bug
  build/built-jar.properties
  build/classes/.netbeans_automatic_build
  build/classes/.netbeans_update_resources
  build/classes/sound/soundController.class
  build/classes/yimsbean/Card.class
  build/classes/yimsbean/CreditController.class
  build/classes/yimsbean/Deck.class
  build/classes/yimsbean/Enemy.class
  build/classes/yimsbean/MainController.class
  build/classes/yimsbean/MainMenuController.class
  build/classes/yimsbean/Player.class
  build/classes/yimsbean/YIMSBean.class
  nbproject/private/private.properties
  nbproject/private/private.xml
  nbproject/project.properties
  src/yimsbean/Deck.java
  src/yimsbean/Enemy.java
  src/yimsbean/MainController.java
  src/yimsbean/MainMenuController.java
  src/yimsbean/Player.java
Labels: By KJ, add, bug-fixed

#32 -bug fixed again -remove useless method -add reset method
  build/built-jar.properties
  build/classes/.netbeans_automatic_build
  build/classes/.netbeans_update_resources
  build/classes/image/ImageSet.class
  build/classes/sound/soundController.class
  build/classes/yimsbean/Card.class
  build/classes/yimsbean/CreditController.class
  build/classes/yimsbean/Deck.class
  build/classes/yimsbean/Enemy.class
  build/classes/yimsbean/MainController.class
  build/classes/yimsbean/MainMenuController.class
  build/classes/yimsbean/NewClass.class
  build/classes/yimsbean/Player.class
  build/classes/yimsbean/YIMSBean.class
  nbproject/private/private.properties
  nbproject/project.properties
  src/yimsbean/Deck.java
  src/yimsbean/Enemy.java
  src/yimsbean/MainController.java
  src/yimsbean/MainMenuController.java
  src/yimsbean/Player.java
Labels: By KJ, add, bug-fixed

#34 -added all Special Card Effect
  build/built-jar.properties
  build/classes/.netbeans_automatic_build
  build/classes/.netbeans_update_resources
  build/classes/image/ImageSet.class
  build/classes/sound/soundController.class
  build/classes/yimsbean/Card.class
  build/classes/yimsbean/CreditController.class
  build/classes/yimsbean/Deck.class
  build/classes/yimsbean/Enemy.class
  build/classes/yimsbean/MainController.class
  build/classes/yimsbean/MainMenuController.class
  build/classes/yimsbean/Player.class
  nbproject/private/private.properties
  nbproject/project.properties
  src/yimsbean/Deck.java
  src/yimsbean/Player.java
Labels: By KJ, add, bug-fixed

#37 backend finished + many bug
  build/classes/yimsbean/Deck.class
  build/classes/yimsbean/Enemy.class
  build/classes/yimsbean/MainController.class
  build/classes/yimsbean/Player.class
  nbproject/private/private.properties
  nbproject/project.properties
  src/yimsbean/Deck.java
  src/yimsbean/Enemy.java
  src/yimsbean/Game.java
  src/yimsbean/MainController.java
  src/yimsbean/Player.java
Labels: add, by JarkkyLove

#38 Add win/lose game
  build/classes/yimsbean/Deck.class
  build/classes/yimsbean/Enemy.class
  build/classes/yimsbean/MainController.class
  build/classes/yimsbean/MainMenuController.class
  build/classes/yimsbean/Player.class
  src/yimsbean/Deck.java
  src/yimsbean/Enemy.java
  src/yimsbean/MainController.java
  src/yimsbean/MainMenuController.java
  src/yimsbean/Player.java
Labels: add, by JarkkyLove
